### ISSUE TITLE
doxel-loopback: Adding "PointCloud" model to database

### ISSUE THREAD

**Issue by luxigo** [doxel/doxel-loopback#5]
We need to rattach to the existing Segment model the pointcloud properties we want to display to users:

eg:
- number of poses used for reconstruction
- number of points in the cloud

Database will be updated from the filesystem for new pointclouds when server is (re)started (or preferably, when lb-ng is run manually while the server is running with strong-pm)

Subsequently those properties should be set at the end of the workflow (when the cloud is generated) using a RESTful HTTP request and a dedicated access token.

In the future, a segment could have many pointclouds.

**Comment by bugdanov** [comment]
Segment.pictures are views. 

To update thumbnails on mouseover we need to fetch poses without reading the whole viewer.json

For this we need to add a related model "Pose": 
Pointcloud hasMany poses, pose belongsTo PointCloud and hasOne Picture.
